"""Investment Brief generator.

Takes the final synthesis output and writes a structured Markdown brief
to output/reports/<ticker>_<timestamp>.md.
"""

import os
from datetime import datetime
from pathlib import Path

REPORTS_DIR = Path(__file__).parent / "reports"
REPORTS_DIR.mkdir(exist_ok=True)


def generate_brief(
    ticker: str,
    synthesis: str,
    signal_score: float | None = None,
    alignment_label: str | None = None,
) -> Path:
    """Write an investment brief Markdown file.

    Args:
        ticker: Stock ticker symbol.
        synthesis: Full synthesis chain output (the brief text).
        signal_score: Optional numeric score (0-100).
        alignment_label: Optional alignment label string.

    Returns:
        Path to the written Markdown file.
    """
    ts = datetime.utcnow().strftime("%Y%m%d_%H%M%S")
    filename = REPORTS_DIR / f"{ticker.upper()}_{ts}.md"

    score_line = f"**Signal Score:** {signal_score}/100\n" if signal_score is not None else ""
    alignment_line = f"**Signal Alignment:** {alignment_label}\n" if alignment_label else ""

    content = f"""# Investment Brief: {ticker.upper()}
*Generated: {datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")}*

{score_line}{alignment_line}
---

{synthesis}

---
*This brief was generated by the Investment Signal Agent. Not financial advice.*
"""

    filename.write_text(content)
    print(f"[output] Brief written → {filename}")
    return filename


def list_reports(ticker: str | None = None) -> list[Path]:
    """List all generated report files, optionally filtered by ticker."""
    pattern = f"{ticker.upper()}_*.md" if ticker else "*.md"
    return sorted(REPORTS_DIR.glob(pattern), reverse=True)


if __name__ == "__main__":
    print("=== investment_brief local test ===")
    sample_synthesis = """## Executive Summary
NVIDIA demonstrates exceptional fundamental momentum with 427% YoY revenue growth
driven by AI infrastructure buildout. Near-term risks from export controls and
elevated valuation are manageable given the demand backdrop.

## Recommended Action
**BUY** — Initiate a 2-3% position on pullbacks toward the 50-day moving average.

## Conviction Level
**HIGH** — All signal categories (fundamental, momentum, sentiment) point bullish;
only macro (elevated rates) provides a mild headwind.

## Key Risks
- US export restrictions on H100/A100/Blackwell chips to China
- Valuation multiple compression if AI capex spending decelerates
- AMD/Intel competitive pressure in inference accelerators
- Macro-driven risk-off rotation out of high-multiple tech

## Monitoring Triggers
- Quarterly gross margin below 70%
- Expansion of chip export controls to additional geographies
- Hyperscaler earnings guidance cut on AI capex
"""
    path = generate_brief("NVDA", sample_synthesis, signal_score=82.0, alignment_label="BULL")
    print(f"Report saved: {path}")
    print(f"All NVDA reports: {[str(p.name) for p in list_reports('NVDA')]}")
