"""ThoughtNode dataclass — a single node in the Tree-of-Thoughts beam search."""

from dataclasses import dataclass, field
from typing import Optional


@dataclass
class ThoughtNode:
    """Represents one investment-thesis branch at a given depth in the tree.

    Attributes:
        ticker: The stock ticker this node belongs to.
        branch: Branch label: "A" (Bullish), "B" (Bearish), "C" (Neutral), "D" (Contrarian).
        depth: Current depth in the tree (0 = root stances, 1+ = elaborations).
        content: The thesis text for this node.
        score: Evaluator score in [0, 10]. None until evaluated.
        parent: The parent ThoughtNode, or None for root nodes.
        children: Child nodes generated by expanding this node.
    """

    ticker: str
    branch: str
    depth: int
    content: str
    score: Optional[float] = None
    parent: Optional["ThoughtNode"] = None
    children: list["ThoughtNode"] = field(default_factory=list)

    def is_evaluated(self) -> bool:
        return self.score is not None

    def lineage(self) -> list["ThoughtNode"]:
        """Return the path from root to this node (inclusive)."""
        path = []
        node: Optional[ThoughtNode] = self
        while node is not None:
            path.append(node)
            node = node.parent
        return list(reversed(path))

    def summary(self) -> str:
        score_str = f"{self.score:.2f}" if self.score is not None else "?"
        return f"[{self.ticker}|{self.branch}|d={self.depth}|score={score_str}] {self.content[:80]}"

    def __repr__(self) -> str:
        return self.summary()


if __name__ == "__main__":
    print("=== thought_node local test ===")
    root = ThoughtNode(ticker="NVDA", branch="A", depth=0, content="Bullish: Record AI chip demand.", score=8.5)
    child = ThoughtNode(ticker="NVDA", branch="A", depth=1, content="Data-center orders up 4x YoY.", score=9.0, parent=root)
    root.children.append(child)

    for node in child.lineage():
        print(" ", node)
