"""ThoughtNode dataclass — a single node in the Tree-of-Thoughts beam search.

Updated for the 7-agent architecture:
  - branch follows the four canonical types (A/B/C/D)
  - includes counter_evidence as a required field
  - score is on the 0-100 Critic rubric scale
"""

from dataclasses import dataclass, field
from typing import Optional


BRANCH_LABELS = {
    "A": "Capital-Led",
    "B": "Adoption-Led",
    "C": "Risk-Adjusted",
    "D": "Evidence-Insufficient",
}


@dataclass
class ThoughtNode:
    """One investment-thesis branch node at a given depth in the ToT tree.

    Attributes:
        ticker:           The technology category this node belongs to.
        branch:           "A" (Capital-Led) | "B" (Adoption-Led) |
                          "C" (Risk-Adjusted) | "D" (Evidence-Insufficient).
        depth:            0 = root stances, 1 = child refinements.
        content:          The thesis text for this node.
        counter_evidence: Non-trivial argument that could invalidate the stance.
                          Required — empty/vague entries are gated by Orchestrator.
        score:            Critic rubric score (0-100). None until evaluated.
        parent:           Parent ThoughtNode, or None for root nodes.
        children:         Child nodes generated by expanding this node.
    """

    ticker: str
    branch: str
    depth: int
    content: str
    counter_evidence: str = ""
    score: Optional[float] = None
    parent: Optional["ThoughtNode"] = None
    children: list["ThoughtNode"] = field(default_factory=list)

    def is_evaluated(self) -> bool:
        return self.score is not None

    def lineage(self) -> list["ThoughtNode"]:
        """Return the path from root to this node (inclusive)."""
        path = []
        node: Optional[ThoughtNode] = self
        while node is not None:
            path.append(node)
            node = node.parent
        return list(reversed(path))

    def branch_label(self) -> str:
        return BRANCH_LABELS.get(self.branch, self.branch)

    def summary(self) -> str:
        score_str = f"{self.score:.0f}/100" if self.score is not None else "?"
        return (
            f"[{self.ticker}|{self.branch}({self.branch_label()})|"
            f"d={self.depth}|score={score_str}] {self.content[:80]}"
        )

    def __repr__(self) -> str:
        return self.summary()


if __name__ == "__main__":
    print("=== thought_node local test ===")
    root = ThoughtNode(
        ticker="ai_ml_infrastructure",
        branch="A",
        depth=0,
        content="Capital-Led: Hyperscaler GPU commitments signal sustained AI infrastructure demand.",
        counter_evidence="Export controls on H100/A100 chips could materially reduce addressable market.",
        score=72,
    )
    child = ThoughtNode(
        ticker="ai_ml_infrastructure",
        branch="A",
        depth=1,
        content="Blackwell GPU backlog of 3+ quarters provides forward visibility on demand.",
        counter_evidence="Blackwell yields remain below target; delivery timelines may slip.",
        score=81,
        parent=root,
    )
    root.children.append(child)

    for node in child.lineage():
        print(" ", node)
    print(f"\nRoot evaluated: {root.is_evaluated()}")
    print(f"Child lineage depth: {len(child.lineage())}")
