"""Output-Time Guardrails — Step 5.

Three functions applied after synthesis generates the report draft:

1. prepend_disclaimer()
   Every report opens with a scope disclaimer making clear it is
   decision-support, not investment advice.

2. audit_citation_groundedness()
   LLM-based audit: given the report text and all source evidence, identify
   any specific claims in the report that cannot be verified from the evidence.
   Unsupported claims are marked [⚠ UNSUPPORTED] and the run is flagged for
   Level 3 review. The report is not delivered until a human resolves the flag.

3. enforce_confidence_stance_consistency()
   Assigns ConfidenceLevel to each CategoryResult using the consistency rules
   below and appends Level 1 in-brief flags where appropriate:

   BUY  + final_score ≥ 80 + not variance_triggered → HIGH
   BUY  + final_score 65–79                          → MEDIUM
   BUY  + variance_triggered                         → MEDIUM
   HOLD                                              → MEDIUM (inherently uncertain)
   REDUCE + final_score ≤ 30 + not variance_triggered → HIGH (strong bear signal)
   REDUCE + final_score 30–40                         → MEDIUM
   MANUAL_REVIEW                                      → LOW (always)
   Branch D (EVIDENCE_INSUFFICIENT) winner            → LOW
"""

from __future__ import annotations

import json
import os
import re
from datetime import datetime, timezone

from langchain_ollama import ChatOllama
from langchain_core.prompts import PromptTemplate
from langchain_core.output_parsers import StrOutputParser

from schemas.messages import (
    CategoryResult,
    ConfidenceLevel,
    InvestmentStance,
    BranchType,
    SynthesisPackage,
)

LLM_MODEL = os.getenv("AGENT_LLM", "granite3.3:8b")

SCOPE_DISCLAIMER = """> **Scope Disclaimer** — This report is generated by an automated agentic system \
from public data sources (SEC EDGAR, GitHub, NewsData.io, FRED, Google Trends). \
It is intended as **decision-support** for engineering leaders, not as investment advice. \
All stances should be validated against your organisation's internal data, current market \
conditions, and professional financial guidance before acting. \
Confidence levels reflect signal alignment, not certainty of outcomes. \
Data freshness and source availability are noted where applicable.\
"""

_AUDIT_PROMPT = PromptTemplate.from_template(
    """You are a citation auditor reviewing an investment report for unsupported claims.

SOURCE EVIDENCE AVAILABLE:
{evidence_summary}

REPORT DRAFT:
{report_text}

Task: Identify any specific factual claims in the report (numerical figures, company-specific
statements, market data) that CANNOT be verified from the source evidence above.
A claim is unsupported if:
  - It cites a specific number not present in the evidence
  - It attributes a statement to a company without a corresponding passage
  - It makes a forward projection not derivable from the source data

List only genuinely unsupported claims. If all claims are grounded, return an empty list.

Respond with ONLY valid JSON:
{{"unsupported_claims": ["<claim 1>", "<claim 2>"], "audit_passed": <true|false>}}
"""
)


def prepend_disclaimer(report_text: str, run_id: str, cycle_date: str) -> str:
    """Prepend the scope disclaimer and run metadata to the report."""
    header = (
        f"{SCOPE_DISCLAIMER}\n\n"
        f"*Run ID: `{run_id}` | Cycle: {cycle_date} | "
        f"Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}*\n\n---\n\n"
    )
    return header + report_text


def _build_evidence_summary(pkg: SynthesisPackage) -> str:
    """Build a concise evidence summary string for the citation audit prompt."""
    lines = []
    for result in pkg.category_results:
        lines.append(f"Category: {result.category_label}")
        lines.append(f"  Stance: {result.stance.value}  Score: {result.final_score:.0f}/100")
        if result.reasoning_trace:
            lines.append(f"  Trace: {result.reasoning_trace[:200]}")
    if pkg.emerging_candidates:
        lines.append(f"Emerging: {', '.join(pkg.emerging_candidates)}")
    if pkg.emerging_rationale:
        lines.append(f"Emerging rationale: {pkg.emerging_rationale[:200]}")
    return "\n".join(lines) or "No structured evidence available."


def audit_citation_groundedness(
    report_text: str,
    pkg: SynthesisPackage,
) -> tuple[bool, list[str]]:
    """LLM-based citation groundedness audit.

    Returns:
        (audit_passed, unsupported_claims)
        audit_passed=False triggers a Level 3 HALT.
    """
    evidence_summary = _build_evidence_summary(pkg)
    # Truncate report to keep prompt manageable
    truncated_report = report_text[:3000]

    try:
        llm = ChatOllama(model=LLM_MODEL, temperature=0.1)
        chain = _AUDIT_PROMPT | llm | StrOutputParser()
        raw = chain.invoke({
            "evidence_summary": evidence_summary,
            "report_text": truncated_report,
        })
        match = re.search(r"\{.*\}", raw, re.DOTALL)
        if match:
            data = json.loads(match.group())
            claims = [str(c) for c in data.get("unsupported_claims", [])]
            passed = bool(data.get("audit_passed", not claims))
            return passed, claims
    except Exception as e:
        print(f"[OutputAudit] Citation audit LLM call failed: {e} — defaulting to pass")

    return True, []


def _mark_unsupported_in_report(report_text: str, unsupported_claims: list[str]) -> str:
    """Append an unsupported-claims annex to the report draft (does not strip content).

    The report is held at Level 3; the annex makes the issue explicit for the reviewer.
    """
    if not unsupported_claims:
        return report_text
    annex = "\n\n---\n\n## ⚠ Citation Audit — Unsupported Claims (HOLD FOR REVIEW)\n\n"
    annex += "The following claims could not be verified against source evidence:\n\n"
    for i, claim in enumerate(unsupported_claims, 1):
        annex += f"{i}. {claim}\n"
    annex += (
        "\n*This report is on LEVEL 3 HOLD. Do not act on stances until a human reviewer "
        "resolves or removes these claims.*\n"
    )
    return report_text + annex


def compute_confidence_level(result: CategoryResult) -> ConfidenceLevel:
    """Derive ConfidenceLevel from stance, score, and manual_review_flag."""
    if result.manual_review_flag or result.stance == InvestmentStance.MANUAL_REVIEW:
        return ConfidenceLevel.LOW
    if result.winning_branch == BranchType.EVIDENCE_INSUFFICIENT:
        return ConfidenceLevel.LOW

    score = result.final_score

    if result.stance == InvestmentStance.BUY:
        if score >= 80:
            return ConfidenceLevel.HIGH
        return ConfidenceLevel.MEDIUM

    if result.stance == InvestmentStance.HOLD:
        return ConfidenceLevel.MEDIUM

    if result.stance == InvestmentStance.REDUCE:
        if score <= 30:
            return ConfidenceLevel.HIGH
        return ConfidenceLevel.MEDIUM

    return ConfidenceLevel.MEDIUM


def enforce_confidence_stance(
    results: list[CategoryResult],
) -> list[CategoryResult]:
    """Assign ConfidenceLevel to each result and append Level 1 in-brief flags.

    Mutates the confidence_level and in_brief_flags fields in place and returns
    the updated list.
    """
    updated = []
    for result in results:
        confidence = compute_confidence_level(result)
        flags = list(result.in_brief_flags)

        if confidence == ConfidenceLevel.LOW:
            flags.append(
                f"LOW confidence on {result.stance.value} stance "
                f"(score={result.final_score:.0f}/100) — validate before acting"
            )

        updated.append(result.model_copy(update={
            "confidence_level": confidence,
            "in_brief_flags": flags,
        }))
    return updated


def run_output_guardrails(
    report_text: str,
    pkg: SynthesisPackage,
) -> tuple[str, bool, list[str]]:
    """Run all output-time guardrails in order.

    Returns:
        (final_report_text, citation_audit_passed, unsupported_claims)
    """
    # 1. Enforce confidence-stance consistency (updates pkg.category_results)
    pkg.category_results = enforce_confidence_stance(pkg.category_results)

    # 2. Citation groundedness audit
    audit_passed, unsupported = audit_citation_groundedness(report_text, pkg)
    if not audit_passed:
        report_text = _mark_unsupported_in_report(report_text, unsupported)

    # 3. Prepend scope disclaimer
    final = prepend_disclaimer(report_text, pkg.run_id, pkg.cycle_date)

    return final, audit_passed, unsupported


if __name__ == "__main__":
    from schemas.messages import (
        SynthesisPackage, CategoryResult, AlignmentClassification, BranchType,
    )
    print("=== output_audit local test ===")

    results = [
        CategoryResult(
            category_id="ai_ml", category_label="AI / ML Infrastructure",
            classification=AlignmentClassification.ALIGNED,
            stance=InvestmentStance.BUY, final_score=78.0,
        ),
        CategoryResult(
            category_id="cybersecurity", category_label="Cybersecurity",
            classification=AlignmentClassification.CONTRADICTORY,
            stance=InvestmentStance.MANUAL_REVIEW, final_score=50.0,
            manual_review_flag=True,
        ),
    ]
    updated = enforce_confidence_stance(results)
    for r in updated:
        print(f"  {r.category_label}: {r.stance.value}  confidence={r.confidence_level.value}")
        for flag in r.in_brief_flags:
            print(f"    ⚑ {flag}")

    disclaimer = prepend_disclaimer("# Report\n\nSome report content.", "test-001", "2026-06-16")
    print(f"\nDisclaimer prepended: {disclaimer[:200]}…")
